spring:
  profiles:
    active: dev
  redis:
    database: 0 #Redis数据库索引（默认为0）
    host: localhost #redis服务地址
    port: 6379 #redis服务端口
    password: redis #redis服务密码
    pool:
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）;如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-wait: -1 #连接池最大阻塞等待时间（负数表示没有限制）;等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
      max-idle: 8 #连接池最大的空闲链接;默认值也是8。
      min-idle: 0 #连接池最小空闲连接，默认值也是0。
    timeout: 0 #连接超时时间（毫秒）
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/orjrs?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: mysql5720 #mysql版本号
  jpa:
    hibernate:
      ddl-auto: update #create create-dorp validate
    show-sql: true