spring:
  profiles:
    active: dev
  redis:
    database: 0
    host: localhost
    port: 6379
    password: redis
    pool:
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（负数表示没有限制）
      max-idle: 8 #连接池最大的空闲链接
      min-idle: 0 #连接池最小空闲连接
    timeout: 0 #连接超时时间（毫秒）
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/orjrs
    username: root
    password: mysql5720 #mysql版本号
  jpa:
    hibernate:
      ddl-auto: update #create create-dorp validate
    show-sql: true